# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build" and "deploy"
  build and deploy:
    # 服务器环境：最新版 Ubuntu
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Node.js v14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install
        run: npm install # 安装依赖

      - name: Build
        run: npm run build # 打包
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3 # 使用部署到 GitHub pages 的 action
        with:
          publish_dir: ./docs/.vuepress/dist # 部署打包后的 dist 目录
          github_token: ${{ secrets.ACCESS_TOKEN }} # secret 名
          # user_name: ${{ secrets.MY_USER_NAME }}
          # user_email: ${{ secrets.MY_USER_EMAIL }}
          commit_message: build and restart # 部署时的 git 提交信息，自由填写
      # 部署到zhangyh.com.cn服务器
      - name: rsync deployments
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with: 
          username: 'root'   #ssh user name
          server: '${{ secrets.SERVER_IP }}' #引用之前创建好的secret
          ssh_private_key: ${{ secrets.PRIVATE_KEY }} #引用之前创建好的secret
          local_path: './docs/.vuepress/dist'  # 对应我们项目build的文件夹路径
          remote_path: '/usr/share/nginx/html/blog'

